### PR TITLE
Minor clarity/wording changes to README

### PR DESCRIPTION
**Pull request by andre-merzky**
Hello! Thanks for the lovely library.

I found a couple places in the README where the wording/punctuation could help make things a little more clear, so that's the contents of this (small) pull request. Hope this is helpful!

---

This PR was transplanted from ilanschnell/bitarray/pull/23

### CODE REVIEW

**Comment by diamondman** [comment]
I went through a bunch of the easy PRs and merged them. This was one of them. Thanks though :).
https://github.com/diamondman/bitarray/pull/11

**Comment by diamondman** [comment]
It is weird to me that this said it could be merged when I had already pulled in this commit. Maybe I missed something?

**Comment by andre-merzky** [comment]
Ah, sorry, I missed that.  Thanks for adding the forward links.  Not sure why the PR got then created though  either :/

**Comment by diamondman** [comment]
No worries. Thanks for helping out. I just felt I had to keep pulling my weight to be worthy of calling myself the maintainer :). Particularly after all the work that was done in the SIMD PR!

**Pull request closed without merging**
