### PR TITLE
Refactor4fork

### PR DESCRIPTION
**Pull request by diamondman**
Moved tests around into a more modern form, and added Continuous Integration.
https://travis-ci.org/diamondman/bitarray

### CODE REVIEW

**Comment by diamondman** [comment]
@andre-merzky

**Comment by andre-merzky** [comment]
Looks good to me!

**Review by andre-merzky — APPROVED** [review]
Should be merged.
I did not try to run tests, but travis seems to be happy, so... :)

**Comment by diamondman** [comment]
@andre-merzky That is the point of a CI :)

**Pull request merged**
